const Locations = [
  { label: "Jerusalem", value: "Jerusalem" },
  { label: "Tel Aviv Jaffa", value: "Tel Aviv Jaffa" },
  { label: "Haifa", value: "Haifa" },
  { label: "Rishon Lezion", value: "Rishon Lezion" },
  { label: "Petah Tikva", value: "Petah Tikva" },
  { label: "Ashdod", value: "Ashdod" },
  { label: "Netanya", value: "Netanya" },
  { label: "Beer Sheva", value: "Beer Sheva" },
  { label: "Bnei Brak", value: "Bnei Brak" },
  { label: "Holon", value: "Holon" },
  { label: "Ramat Gan", value: "Ramat Gan" },
  { label: "Ashkelon", value: "Ashkelon" },
  { label: "streets", value: "streets" },
  { label: "Beit Shemesh", value: "Beit Shemesh" },
  { label: "Bat Yam", value: "Bat Yam" },
  { label: "Kfar Saba", value: "Kfar Saba" },
  { label: "Herzliya", value: "Herzliya" },
  { label: "Hadera", value: "Hadera" },
  { label: "Modi'in Maccabim-Reut", value: "Modi'in Maccabim-Reut" },
  { label: "Lod", value: "Lod" },
  { label: "Modi'in Illit", value: "Modi'in Illit" },
  { label: "Nazareth", value: "Nazareth" },
  { label: "Ramla", value: "Ramla" },
  { label: "fresh", value: "fresh" },
  { label: "trough", value: "trough" },
  { label: "Rosh HaAyin", value: "Rosh HaAyin" },
  { label: "Hod Hasharon", value: "Hod Hasharon" },
  { label: "Beitar Illit", value: "Beitar Illit" },
  { label: "Givatayim", value: "Givatayim" },
  { label: "Kiryat Ata", value: "Kiryat Ata" },
  { label: "Nahariya", value: "Nahariya" },
  { label: "Qiryat Gat", value: "Qiryat Gat" },
  { label: "Umm al-Fahm", value: "Umm al-Fahm" },
  { label: "Afula", value: "Afula" },
  { label: "Eilat", value: "Eilat" },
  { label: "Ness Ziona", value: "Ness Ziona" },
  { label: "Acre", value: "Acre" },
  { label: "Yavne", value: "Yavne" },
  { label: "Elad", value: "Elad" },
  { label: "Ramat Hasharon", value: "Ramat Hasharon" },
  { label: "Carmiel", value: "Carmiel" },
  { label: "Tiberias", value: "Tiberias" },
  { label: "Kiryat Motzkin", value: "Kiryat Motzkin" },
  { label: "Taiba", value: "Taiba" },
  { label: "Shafram", value: "Shafram" },
  {
    label: "The view of the Galilee",
    value: "The view of the Galilee",
  },
  { label: "Kiryat Bialik", value: "Kiryat Bialik" },
  { label: "Kiryat Ono", value: "Kiryat Ono" },
  { label: "Kiryat Yam", value: "Kiryat Yam" },
  { label: "routes", value: "routes" },
  { label: "Ma'ale Adumim", value: "Ma'ale Adumim" },
  { label: "Or Yehuda", value: "Or Yehuda" },
  { label: "Zefat", value: "Zefat" },
  { label: "Dimona", value: "Dimona" },
  { label: "Tamra", value: "Tamra" },
  { label: "horizons", value: "horizons" },
  { label: "Sakhenin", value: "Sakhenin" },
  { label: "Baqa al-Gharbiya", value: "Baqa al-Gharbiya" },
  { label: "Yehud-Monoson", value: "Yehud-Monoson" },
  { label: "Sderot", value: "Sderot" },
  { label: "Be'er Ya'akov", value: "Be'er Ya'akov" },
  { label: "Givat Shmuel", value: "Givat Shmuel" },
  { label: "Arad", value: "Arad" },
  { label: "castle", value: "castle" },
  { label: "Araba", value: "Araba" },
  { label: "Kfar Yona", value: "Kfar Yona" },
  { label: "Migdal Haemek", value: "Migdal Haemek" },
  { label: "Kiryat Malachi", value: "Kiryat Malachi" },
  { label: "Kafr Qasim", value: "Kafr Qasim" },
  { label: "Tirat Carmel", value: "Tirat Carmel" },
  { label: "Yokneam Illith", value: "Yokneam Illith" },
  { label: "Nesher", value: "Nesher" },
  { label: "Kalanswa", value: "Kalanswa" },
  { label: "Kiryat Shmona", value: "Kiryat Shmona" },
  { label: "Tarshiha", value: "Tarshiha" },
  { label: "Ariel", value: "Ariel" },
  { label: "Or Akiva", value: "Or Akiva" },
  { label: "Beit Shean", value: "Beit Shean" },
];

export default Locations;
